### PR TITLE
Add FAIcon to TabItem

### PR DESCRIPTION
**Pull request by MangelMaxime**
@flozz Here is my proposition for adding FAIcon to the TabItem.

### CODE REVIEW

**Comment by flozz** [comment]
Hello,

I reviewed your PR, and it is almost good, there is only a small points to update: the getters/setters for the `leftIconVisible` and `rightIconVisible` are missing:

```javascript
    /**
     * Define if the left icon is displayed or hidden.
     *
     * @property leftIconVisible
     * @type Boolean
     * @default true
     */
    _leftIconVisible: true,

    isLeftIconVisible: function () {
        return this._leftIconVisible;
    },

    setLeftIconVisible: function (leftIconVisible) {
        this._leftIconVisible = leftIconVisible;
        this._update();
    },

    /**
     * Define if the right icon is displayed or hidden.
     *
     * @property rightIconVisible
     * @type Boolean
     * @default true
     */
    _rightIconVisible: true,

    isRightIconVisible: function () {
        return this._rightIconVisible;
    },

    setRightIconVisible: function (rightIconVisible) {
        this._rightIconVisible = rightIconVisible;
        this._update();
    },
```

**Comment by flozz** [comment]
Oh and I found a little typo `Definie if the tabItem title is displayed or hiddin.` ← `hidden` ;)

**Comment by MangelMaxime** [comment]
Thanks for your reviewed I will fix it today.

**Comment by MangelMaxime** [comment]
Fix :
- the getters/setters for the `leftIconVisible` and `rightIconVisible`
- Typo for `hiddin` ← `hidden`

**Comment by flozz** [comment]
Thank you! :)

**Pull request merged**
